<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#潜在语义模型" data-toc-modified-id="潜在语义模型-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>潜在语义模型</a></span></li><li><span><a href="#潜在语义分析（LSA）" data-toc-modified-id="潜在语义分析（LSA）-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>潜在语义分析（LSA）</a></span><ul class="toc-item"><li><span><a href="#数据集合" data-toc-modified-id="数据集合-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>数据集合</a></span></li><li><span><a href="#分词" data-toc-modified-id="分词-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>分词</a></span></li><li><span><a href="#建立结构化数据集" data-toc-modified-id="建立结构化数据集-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>建立结构化数据集</a></span></li><li><span><a href="#奇异值分解（SVD）" data-toc-modified-id="奇异值分解（SVD）-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>奇异值分解（SVD）</a></span></li><li><span><a href="#非负矩阵分解" data-toc-modified-id="非负矩阵分解-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>非负矩阵分解</a></span></li></ul></li><li><span><a href="#概率潜在语义分析(pLSA)" data-toc-modified-id="概率潜在语义分析(pLSA)-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>概率潜在语义分析(pLSA)</a></span></li><li><span><a href="#潜在狄利克雷分配(LDA)" data-toc-modified-id="潜在狄利克雷分配(LDA)-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>潜在狄利克雷分配(LDA)</a></span><ul class="toc-item"><li><span><a href="#Gibbs抽样" data-toc-modified-id="Gibbs抽样-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Gibbs抽样</a></span><ul class="toc-item"><li><span><a href="#初始化" data-toc-modified-id="初始化-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>初始化</a></span></li><li><span><a href="#训练" data-toc-modified-id="训练-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>训练</a></span></li></ul></li></ul></li><li><span><a href="#20新闻组数据集" data-toc-modified-id="20新闻组数据集-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>20新闻组数据集</a></span><ul class="toc-item"><li><span><a href="#下载停止词汇" data-toc-modified-id="下载停止词汇-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>下载停止词汇</a></span></li><li><span><a href="#20新闻组语料库" data-toc-modified-id="20新闻组语料库-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>20新闻组语料库</a></span></li><li><span><a href="#预处理" data-toc-modified-id="预处理-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>预处理</a></span></li><li><span><a href="#结构化数据" data-toc-modified-id="结构化数据-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>结构化数据</a></span></li><li><span><a href="#SVD_LSA" data-toc-modified-id="SVD_LSA-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>SVD_LSA</a></span></li><li><span><a href="#NMF_LSA" data-toc-modified-id="NMF_LSA-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>NMF_LSA</a></span></li><li><span><a href="#pLSA" data-toc-modified-id="pLSA-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>pLSA</a></span></li><li><span><a href="#LDA" data-toc-modified-id="LDA-5.8"><span class="toc-item-num">5.8&nbsp;&nbsp;</span>LDA</a></span></li></ul></li><li><span><a href="#Bakcups" data-toc-modified-id="Bakcups-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Bakcups</a></span><ul class="toc-item"><li><span><a href="#随机梯度下降-(Stochastic-gradient-descent)" data-toc-modified-id="随机梯度下降-(Stochastic-gradient-descent)-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>随机梯度下降 (Stochastic gradient descent)</a></span><ul class="toc-item"><li><span><a href="#the-pLSA" data-toc-modified-id="the-pLSA-6.1.1"><span class="toc-item-num">6.1.1&nbsp;&nbsp;</span>the pLSA</a></span></li><li><span><a href="#the-LDA" data-toc-modified-id="the-LDA-6.1.2"><span class="toc-item-num">6.1.2&nbsp;&nbsp;</span>the LDA</a></span></li></ul></li></ul></li></ul></div>

# 潜在语义模型

主要参考赵航的书

In [1]:
import numpy as np
import itertools
import string

def document_to_terms(doc, stop_words={""}):
    
    stop_words = set(stop_words)
    alphas = string.ascii_letters
    doc_terms=[]
    term = []
    for char in doc:
        if char in alphas:
            term.append(char)
        else:
            if len(term) != 0:
                word = "".join(term)
                term=[]
                if word.lower() not in stop_words:
                    doc_terms.append(word)
                    
    if len(term) != 0:
        word = "".join(term)
        term=[]
        if word.lower() not in stop_words:
            doc_terms.append(word)
            
    return doc_terms


class StructuredDocuments:
    
    def set_documents(self, documents, stop_words=[""], threshold = 0):
        
        
        
        terms_count = { }
        stop_words_set = set(stop_words)
        for doc in documents:
            doc_terms = document_to_terms(doc, stop_words=stop_words_set)
            
            for term in doc_terms:
                lower_term = term.lower()
                if lower_term not in terms_count:
                    terms_count[lower_term] = 0
                terms_count[lower_term] += 1
        
        for term in terms_count:
            n = terms_count[term]
            if n < threshold:
                stop_words_set.add(term)
                
                
        terms = []
        terms_set = set()
        term_to_index = { }
        docs_terms = []
        docs_term_indices = []
                
        
        for doc in documents:
            doc_terms = document_to_terms(doc, stop_words=stop_words_set)
            # numpy array
            doc_term_indices = np.zeros(len(doc_terms), dtype=np.int)
            
            for n, term in enumerate(doc_terms):
                lower_term = term.lower()
                if lower_term not in terms_set:
                    term_to_index[lower_term] = len(terms)
                    terms_set.add(lower_term)
                    terms.append(lower_term)
                doc_term_indices[n] = term_to_index[lower_term]
                    
            docs_terms.append(doc_terms)            
            docs_term_indices.append(doc_term_indices)
                    
        self.documents_ = documents
        self.terms_ = terms
        self.terms_set_ = terms_set
        self.term_to_index_ = term_to_index
        self.docs_terms_ = docs_terms
        
        self.n_terms = len(terms)
        self.n_documents = len(documents)
        self.docs_term_indices = docs_term_indices
        
        self.stop_words_set = stop_words_set
    
    def print_info(self, n = None, n_shown_terms = 20):
        sdocs = self
        print("%d terms found in %d documents."%(len(sdocs.terms_), len(sdocs.documents_)))
        
        print("terms:", [term for term in itertools.islice(sdocs.terms_, n_shown_terms)])
        print("terms_set:", [term for term in itertools.islice(sdocs.terms_set_, n_shown_terms)])
        
        print("term_to_index:", [(term,sdocs.term_to_index_[term]) for term in itertools.islice(sdocs.term_to_index_, n)])
        print("docs_terms:", [ [word for word in itertools.islice(term, n)]\
                                  for term in itertools.islice(sdocs.docs_terms_, n)])
        print("docs_term_indices:", [[idx for idx in itertools.islice(term, n)]\
                                for term in itertools.islice(sdocs.docs_term_indices, n)])

class LSABase:
    
    def set_documents(self, documents, stop_words=[""], threshold = 0):
        sdocs = StructuredDocuments()
        sdocs.set_documents(documents, stop_words=stop_words, threshold = threshold)
        self.set_structured_documents(sdocs)
        
    def set_structured_documents(self, sdocs):
            
        self.structured_documents = sdocs
        self.n_terms = sdocs.n_terms
        self.n_documents = sdocs.n_documents
        self.docs_term_indices = sdocs.docs_term_indices
        
        
    # set(_structured)_documents first
    def TFIDF(self):
        # terms-documents matrix
        
        n_terms = self.n_terms
        n_documents = self.n_documents
        docs_term_indices = self.docs_term_indices
        
        tf_ij = np.zeros((n_terms, n_documents))
        tf_j = np.zeros(n_documents)  # number of terms in document j 
        df_i = np.zeros(n_terms)  # number of documents which contain term i
        df = n_documents


        term_doc_mat = np.zeros((n_terms, n_documents))
        for j, doc_term_indices in enumerate(docs_term_indices):
            
            tf_j[j] = len(doc_term_indices)

            add_to_df_i = np.zeros(n_terms)
            
            for i in doc_term_indices:                
                
                tf_ij[i][j] += 1
                
                add_to_df_i[i] = 1

            df_i += add_to_df_i

        # in case, no show word
        IDF = np.log(df/np.maximum(df_i, 1))
        # X in hang's book
        # in case empty document
        term_doc_mat = tf_ij/np.maximum(tf_j, 1)*IDF[:,np.newaxis]
        
        self.tf_ij = tf_ij
        self.tf_j = tf_j
        self.df_i = df_i
        self.df = df
        self.IDF = IDF
        self.tfidf = term_doc_mat
        self.term_doc_mat = term_doc_mat

    
    # set(_structured)_documents first
    def TF(self):
        self.TFIDF()
        self.term_doc_mat = self.tf_ij / np.maximum(self.tf_j, 1)     
    
    def print_mat(self, **kargs):
        print_mat(self, **kargs)

    def print_doc_doc_similarity(self):
        print_doc_doc_similarity(self)
    
    
    

def print_mat(lsa, max_topics=None, max_terms=None, max_docs=None, topic_names=None):
    #print_doc_topic_mat(lsa, max_topics=max_topics, topic_names=topic_names)
    print_doc_vectors(lsa, max_topics=max_topics, max_docs=max_docs, topic_names=topic_names)
    print()
    print_topic_vectors(lsa, max_topics=max_topics, max_terms=max_terms, topic_names=topic_names)
             
def print_topic_vectors(lsa, max_topics = None, max_terms = None, topic_names=None):
    if max_topics is None:
        max_topics = 20
    if max_terms is None:
        max_terms = 5
    
    term_topic_mat = lsa.term_topic_mat

    n_terms = lsa.n_terms

    terms = lsa.structured_documents.terms_
    ntopics = term_topic_mat.shape[1]

    ntopics = min(max_topics, ntopics)
    n_terms = min(max_terms, n_terms)
    
    for t in range(ntopics):
        if topic_names is None:
            tname = "topic%d"%t
        else:
            tname = topic_names[t]
            
        ts = "%7s"%tname
        
        print(ts, " = ", end="")
        index = np.argsort(-np.abs(term_topic_mat[:,t]))

        for j in range(n_terms):
            i = index[j]
            print("%+3f*%s"%(term_topic_mat[i, t], terms[i]), end="")
        print()
        
def print_doc_vectors(lsa, max_topics = None, max_docs = None, topic_names=None):
    if max_docs is None:
        max_docs = 10
    if max_topics is None:
        max_topics = 5
    
    topic_doc_mat = lsa.topic_doc_mat

    n_documents = lsa.n_documents
    ntopics = topic_doc_mat.shape[0]

    ntopics = min(max_topics, ntopics)
    n_documents = min(max_docs, n_documents)
    
    for d in range(n_documents):
                     
        ds = "%7s"%("doc%d"%d)        
        print(ds, " = ", end="")
        
        index = np.argsort(-np.abs(topic_doc_mat[:,d]))

        for j in range(ntopics):        
            t = index[j]         
            
            if topic_names is None:
                tname = "topic%d"%t
            else:
                tname = topic_names[t]
            
            print("%+.1e*%s"%(topic_doc_mat[t, d], tname), end="")
        print()
    
    
def print_doc_topic_mat(lsa, max_topics = None, topic_names=None, max_docs=None):
    if max_topics is None:
        max_topics = 20
    if max_docs is None:
        max_docs = 15
        
    term_topic_mat = lsa.term_topic_mat
    topic_doc_mat = lsa.topic_doc_mat

    n_documents = lsa.n_documents
    n_terms = lsa.n_terms

    terms = lsa.structured_documents.terms_
    ntopics = topic_doc_mat.shape[0]    
    
    ntopics = min(ntopics, max_topics)
    n_documents = min(n_documents, max_docs)

    print("%8s"%"document", end="")
    for t in range(ntopics):
        if topic_names is None:
            tname = "topic%d"%t
        else:
            tname = topic_names[t]
             
        ts = " %10s"%tname
        
        print(ts, end="")
    print()

    for i in range(n_documents):
        print("%8d"%i, end="")
        for t in range(ntopics):
            print(" %+.1e"%topic_doc_mat[t, i], end="")
        print()

    print()
    

        
class SVD_LSA(LSABase):
                        
    def topic_decompose(self, ntopics,term_weight = "TFIDF"):        
        if term_weight == "TFIDF":
            self.TFIDF()
        elif term_weight == "TF":
            self.TF()
            
        U, S, VT = np.linalg.svd(self.term_doc_mat, full_matrices=False)
        
        U = U[:,:ntopics]
        VT = VT[:ntopics,:]
        S = S[:ntopics]
        
        self.U = U
        self.S = S
        self.VT = VT
        self.term_topic_mat = U
        self.topic_doc_mat = VT
        self.ntopics = ntopics

# non-negative matrix factorization
def NMF(A, k, max_iters, seed = None, on_update=None):
    # A = [m x n]
    # W = [m x k]
    # H = [k x n]
    if seed is None:
        seed = 0

    m = A.shape[0]
    n = A.shape[1]

    rng = np.random.RandomState(seed=seed)
    W = rng.rand(m, k)
    H = rng.rand(k, n)
    
    for i in range(max_iters):
        Hold = H
        Wold = W
        # update imediately
        #(k,n) =  (k,n) * { [(k,m) (m,n)] / [(k,m)(m,k)(k,n) + epsilon]}  }
        H = H * ((W.T.dot(A)) / (W.T.dot(W).dot(H) + 1E-20))
        # update imediately
        #(k,n) =  (m,k) * { [(m,n) (n,k)] / [(m,k)(k,n)(n,k)]}
        W = W * ((A.dot(H.transpose())) / (W.dot(H.dot(H.transpose())) + 1E-20))
        
        #print(A)
        #print(H)
        #print(W)
        
        #ad-hoc normalization
        scaleW = W.sum(axis=0)
        W = W/scaleW
        H = H*scaleW[:,np.newaxis]
        
        if on_update is not None:
            if on_update(i, H, W, Hold, Wold):
                break

    return W, H

class NMF_LSA(LSABase):

    
        
    def topic_decompose(self, ntopics, term_weight = "TFIDF", max_iters=200,  seed = None, on_update=None):        
        if term_weight == "TFIDF":
            self.TFIDF()
        elif term_weight == "TF":
            self.TF()
            
        n_terms = self.n_terms
        n_documents = self.n_documents
        term_doc_mat = self.term_doc_mat
 
        W, H = NMF(term_doc_mat, ntopics, max_iters = max_iters, seed=seed, on_update=on_update)

        #print(W)
        #print(H)
        
        # ad-hoc normalization
        if term_weight == "TFIDF":
            #print(self.IDF)
            #print(1./np.maximum(self.IDF, 1E-20))
            scaleW = W.T.dot( 1./np.maximum(self.IDF, 1E-20) )
        elif term_weight == "TF":
            scaleW = W.sum(axis=0)
                        
        W = W/scaleW
        H = H*scaleW[:,np.newaxis]
                
        #print(W)
        #print(H)
        
        self.term_topic_mat = W
        self.topic_doc_mat = H
        self.W = W
        self.H = H
        self.ntopics = ntopics
        
class pLSA(LSABase):
    
    def topic_decompose(self, ntopics, max_iters=200, on_update=None, seed=0, alpha=1E-10):

        n_terms = self.n_terms
        n_documents = self.n_documents
        docs_term_indices = self.docs_term_indices
        
        rng = np.random.RandomState(seed=seed)
        Pwz = rng.rand(n_terms, ntopics)
        Pzd = rng.rand(ntopics, n_documents)

        Pwz = Pwz/Pwz.sum(axis=0)
        
        nwd = alpha*np.ones((n_terms, n_documents)) # number of word `w` in document `d`

        for j, doc_term_indices in enumerate(docs_term_indices):                
            for i in doc_term_indices:                                
                nwd[i][j] += 1
  
        for i in range(max_iters):

            nd = nwd.sum(axis=0)

            # add 1E-6 to avoid 0
            # we need to inverse the elements of this matrix
            Pwd = Pwz.dot(Pzd) + 1E-20

            Pwz_new = (nwd/Pwd).dot(Pzd.transpose()) * Pwz
            Pwz_new = Pwz_new / Pwz_new.sum(axis=0)


            Pzd_new = (nwd/Pwd).transpose().dot(Pwz).transpose() * Pzd
            Pzd_new = Pzd_new / nd

            #print(np.power(Pwz_new-Pwz,2).sum())
            #print(np.power(Pzd_new-Pzd,2).sum())
            #print(np.power(Pzd_new,2).sum())
                        
            if on_update is not None:
                if on_update(i, Pwz_new, Pzd_new, Pwz, Pzd):
                    Pwz = Pwz_new
                    Pzd = Pzd_new
                    break

            Pwz = Pwz_new
            Pzd = Pzd_new
            
        self.term_topic_mat = Pwz
        self.topic_doc_mat = Pzd
        self.ntopics = ntopics
        
        
class LDA(LSABase):
        
    # intialization randomly
    # assign each word a topic
    def initialize_randomly(self, ntopics):
        n_documents = self.n_documents
        n_terms = self.n_terms
        
        n_mk = np.zeros((n_documents, ntopics))
        n_kv = np.zeros((ntopics, n_terms))
        n_m = np.zeros(n_documents)
        n_k = np.zeros(ntopics)

        k_mp = n_documents*[None]
        v_mp =  self.docs_term_indices
        
        #assert type(self.docs_term_indices[0]) is np.ndarray
        
        for m in range(n_documents):
            length = len(v_mp[m])
            
            # generate len(doc_terms) random topics
            k = np.random.randint(ntopics, size=length, dtype=np.int)
            
            # assign topic
            k_mp[m] = k[:]
            
            # assign document length
            n_m[m] = length
            
            for p in range(length):
                v = v_mp[m][p]
                n_mk[m, k] += 1 
                n_kv[k,v] += 1 
                n_k[k] += 1

        self.n_mk = n_mk
        self.n_kv = n_kv
        self.n_m = n_m
        self.n_k = n_k
        self.k_mp = k_mp
        self.v_mp = v_mp

    def topic_decompose(self, ntopics, alpha=1, beta=1, warnming_iters=1000, estimate_iters=100, sampling_method="Gibbs"):        
        n_documents = self.n_documents
        n_terms = self.n_terms
        
        self.initialize_randomly(ntopics)
        
        n_mk = self.n_mk
        n_m = self.n_m
        n_kv = self.n_kv
        n_k = self.n_k
        
        theta_mk_sum = np.zeros((n_documents, ntopics))
        phi_kv_sum = np.zeros((ntopics, n_terms))
        
        for _ in range(warnming_iters):
            if sampling_method == "Gibbs":
                self.Gibbs_step(self.zw_Gibbs_topic_prob, alpha, beta)
            else:
                self.MH_step(self.zw_MH_topic_prob, alpha, beta)

        for _ in range(estimate_iters):
            if sampling_method == "Gibbs":
                self.Gibbs_step(self.zw_Gibbs_topic_prob, alpha, beta)
            else:
                self.MH_step(self.zw_MH_topic_prob, alpha, beta)

            #print(n_mk)
            #print(n_kv)
            theta_mk_sum += (n_mk + alpha)/(n_mk + alpha).sum(axis=1, keepdims=True)
            phi_kv_sum += (n_kv + beta)/(n_kv + beta).sum(axis=1, keepdims=True)
        
        theta_mk = theta_mk_sum/estimate_iters
        phi_kv = phi_kv_sum/estimate_iters
        
        self.theta_mk = theta_mk
        self.phi_kv = phi_kv
        self.term_topic_mat = phi_kv.transpose()
        self.topic_doc_mat = theta_mk.transpose()
        
        
    # generate P(z|w) sample
    def zw_Gibbs_topic_prob(self, m, v, alpha, beta):
        n_mk = self.n_mk
        n_m = self.n_m
        n_kv = self.n_kv
        n_k = self.n_k
            
        n_kv_ = (n_kv[:,v] + beta) / (n_kv[:,:] + beta).sum(axis=1)
        n_mk_ = (n_mk[m,:] + alpha) / (n_mk[m,:] + alpha).sum()
        return n_kv_*n_mk_

    # generate P(z|w) sample
    def zw_MH_topic_prob(m, v, k, alpha, beta):
        n_mk = self.n_mk
        n_m = self.n_m
        n_kv = self.n_kv
        n_k = self.n_k
        
        n_kv_ = (n_kv[k,v] + beta) / (n_kv[k,:] + beta).sum()
        n_mk_ = (n_mk[m,k] + alpha) / (n_mk[m,:] + alpha).sum()
        return n_kv_*n_mk_

    
    def MH_step(self, topic_prob, alpha, beta):

        n_documents = self.n_documents

        v_mp = self.v_mp
        k_mp = self.k_mp
        
        n_mk = self.n_mk
        n_m = self.n_m
        n_kv = self.n_kv
        n_k = self.n_k
        
        # random document
        m = np.random.randint(n_document, dtype=np.int)
        # random term
        p = np.random.randint(len(v_mp[m]), dtype=np.int)
        
        v = v_mp[m][p]
        k = k_mp[m][p]    
        
        # random new topic
        kp = np.random.randint(ntopics, dtype=np.int)

        k_prob = topic_prob(m, v, k, alpha, beta)
        kp_prob = topic_prob(m, v, kp, alpha, beta)

        acc = kp_prob / (k_prob + 1E-10)
        u = np.random.rand()
        if u < acc:
            # accept      
            n_mk[m, k] -= 1
            #n_m[m] -= 1
            n_kv[k, v] -= 1
            n_k[k] -= 1

            k_mp[m][p] = kp
            
            n_mk[m, kp] += 1
            #n_m[m] += 1
            n_kv[kp, v] += 1
            n_k[kp] += 1

    
    
    def Gibbs_step(self, sample_topic, alpha, beta):
        n_documents = self.n_documents
        
        v_mp = self.v_mp
        k_mp = self.k_mp
        
        n_mk = self.n_mk
        n_m = self.n_m
        n_kv = self.n_kv
        n_k = self.n_k

        for m in range(n_documents):
            for p in range(len(v_mp[m])):
                
                # current term
                v = v_mp[m][p]

                # current topic
                k = k_mp[m][p]   
                
                n_mk[m, k] -= 1
                #n_m[m] -= 1
                n_kv[k, v] -= 1
                n_k[k] -= 1

                topics_prob = sample_topic(m, v, alpha, beta)
                acc = topics_prob.cumsum()/topics_prob.sum()
                u = np.random.rand()
                kp = np.searchsorted(acc, u, side="left")

                k_mp[m][p] = kp
                
                n_mk[m, kp] += 1
                #n_m[m] += 1
                n_kv[kp, v] += 1
                n_k[kp] += 1





# 潜在语义分析（LSA）

## 数据集合

我们的文档包含两个主题：一个是粒子物理，常用词汇为"meson", "photon"。
另外一个是生活，常用词汇为"girl", "boy"。

In [2]:
# documents set
documents=[
    "Girl loves boy",
    "Boy loves girl",
    "Girl loves girl",
    "Boy loves boy",
    
    "Meson hits photon",
    "Photon hits meson",
    "Photon hits photon",
    "Meson hits meson",

    "Boy loves meson",
    "Girl loves photon",
    "Meson hits girl",
    "Photon hits boy a",
    "",
]

## 分词

In [3]:
print(document_to_terms("a Bc bc 1C", stop_words=["a"]))

['Bc', 'bc', 'C']


## 建立结构化数据集

In [4]:
sdocs = StructuredDocuments()
sdocs.set_documents(documents, threshold=2)
sdocs.print_info()

6 terms found in 13 documents.
terms: ['girl', 'loves', 'boy', 'meson', 'hits', 'photon']
terms_set: ['boy', 'hits', 'meson', 'loves', 'photon', 'girl']
term_to_index: [('girl', 0), ('loves', 1), ('boy', 2), ('meson', 3), ('hits', 4), ('photon', 5)]
docs_terms: [['Girl', 'loves', 'boy'], ['Boy', 'loves', 'girl'], ['Girl', 'loves', 'girl'], ['Boy', 'loves', 'boy'], ['Meson', 'hits', 'photon'], ['Photon', 'hits', 'meson'], ['Photon', 'hits', 'photon'], ['Meson', 'hits', 'meson'], ['Boy', 'loves', 'meson'], ['Girl', 'loves', 'photon'], ['Meson', 'hits', 'girl'], ['Photon', 'hits', 'boy'], []]
docs_term_indices: [[0, 1, 2], [2, 1, 0], [0, 1, 0], [2, 1, 2], [3, 4, 5], [5, 4, 3], [5, 4, 5], [3, 4, 3], [2, 1, 3], [0, 1, 5], [3, 4, 0], [5, 4, 2], []]


我们使用频率逆文档(TFIDF)来表示term-document矩阵。

In [5]:
lsa = LSABase()
lsa.set_documents(documents)
lsa.TFIDF()
with np.printoptions(precision=3):
    print("term-document (%dX%d) matrix setup"%(lsa.term_doc_mat.shape[0],lsa.term_doc_mat.shape[1]))
    print(lsa.tf_ij)
    print(lsa.tf_j)
    print(lsa.df_i)
    print(lsa.tfidf)

term-document (7X13) matrix setup
[[1. 1. 2. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 1. 0. 2. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 0. 2. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 2. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 0.]
[5. 6. 5. 5. 6. 5. 1.]
[[0.319 0.319 0.637 0.    0.    0.    0.    0.    0.    0.319 0.319 0.
  0.   ]
 [0.258 0.258 0.258 0.258 0.    0.    0.    0.    0.258 0.258 0.    0.
  0.   ]
 [0.319 0.319 0.    0.637 0.    0.    0.    0.    0.319 0.    0.    0.239
  0.   ]
 [0.    0.    0.    0.    0.319 0.319 0.    0.637 0.319 0.    0.319 0.
  0.   ]
 [0.    0.    0.    0.    0.258 0.258 0.258 0.258 0.    0.    0.258 0.193
  0.   ]
 [0.    0.    0.    0.    0.319 0.319 0.637 0.    0.    0.319 0.    0.239
  0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.641
  0.   ]]


## 奇异值分解（SVD）

将term-documents矩阵分解为 u s vT
保留其中主值最大的部分。
奇异值分解的正交性要求，矩阵的部分数值小于0，如何解释呢？

In [6]:
lsa = SVD_LSA()
lsa.set_documents(documents)
lsa.topic_decompose(ntopics=2, term_weight="TF")
lsa.print_mat()

   doc0  = +3.3e-01*topic1-3.1e-01*topic0
   doc1  = +3.3e-01*topic1-3.1e-01*topic0
   doc2  = +3.2e-01*topic1-3.2e-01*topic0
   doc3  = +3.4e-01*topic1-3.0e-01*topic0
   doc4  = -3.6e-01*topic1-2.8e-01*topic0
   doc5  = -3.6e-01*topic1-2.8e-01*topic0
   doc6  = -3.5e-01*topic1-2.7e-01*topic0
   doc7  = -3.7e-01*topic1-2.9e-01*topic0
   doc8  = -3.0e-01*topic0+1.1e-01*topic1
   doc9  = -3.0e-01*topic0+1.1e-01*topic1

 topic0  = -0.440937*girl-0.437121*loves-0.415396*meson-0.398767*boy-0.377042*hits
 topic1  = -0.466845*hits+0.430359*loves-0.418304*meson-0.389008*photon+0.381818*boy


## 非负矩阵分解

将term-documents矩阵$X$分解为 $WH$，其中$W$和$H$为（任意元素）非负矩阵。
目标为优化
$$\sum_{ij}(WH-X)_{ij}^2
优化方法采用“乘法更新规则”。

In [7]:
ntopics = 2
print("We want %d topics"%ntopics)

lsa = NMF_LSA()
lsa.set_documents(documents)
lsa.topic_decompose(ntopics=2, term_weight="TF")
lsa.print_mat(topic_names=["live","physics"], max_docs=15)

We want 2 topics
   doc0  = +1.0e+00*physics+3.4e-77*live
   doc1  = +1.0e+00*physics+5.5e-77*live
   doc2  = +1.0e+00*physics+1.9e-24*live
   doc3  = +1.0e+00*physics+0.0e+00*live
   doc4  = +1.0e+00*live+4.8e-48*physics
   doc5  = +1.0e+00*live+4.4e-48*physics
   doc6  = +1.0e+00*live+4.1e-63*physics
   doc7  = +1.1e+00*live+1.9e-36*physics
   doc8  = +6.9e-01*physics+3.3e-01*live
   doc9  = +7.0e-01*physics+3.1e-01*live
  doc10  = +7.2e-01*live+3.2e-01*physics
  doc11  = +5.2e-01*live+2.4e-01*physics
  doc12  = +0.0e+00*live+0.0e+00*physics

   live  = +0.330953*hits+0.328633*meson+0.300137*photon+0.023426*a+0.016849*girl
physics  = +0.342109*loves+0.317835*girl+0.308588*boy+0.014114*meson+0.009756*photon


In [8]:
ntopics = 2
print("We want %d topics"%ntopics)

lsa = NMF_LSA()
lsa.set_documents(documents)
lsa.topic_decompose(ntopics=2, term_weight="TFIDF")
lsa.print_mat(topic_names=["live","physics"], max_docs=15)

We want 2 topics
   doc0  = +1.0e+00*physics+8.7e-105*live
   doc1  = +1.0e+00*physics+1.5e-104*live
   doc2  = +1.0e+00*physics+4.5e-60*live
   doc3  = +1.0e+00*physics+1.1e-304*live
   doc4  = +1.0e+00*live+1.6e-76*physics
   doc5  = +1.0e+00*live+1.5e-76*physics
   doc6  = +1.0e+00*live+2.3e-140*physics
   doc7  = +1.0e+00*live+2.4e-42*physics
   doc8  = +6.4e-01*physics+3.7e-01*live
   doc9  = +6.4e-01*physics+3.6e-01*live
  doc10  = +6.4e-01*live+3.8e-01*physics
  doc11  = +6.5e-01*live+3.3e-01*physics
  doc12  = +0.0e+00*live+0.0e+00*physics

   live  = +0.309315*meson+0.296353*photon+0.255493*hits+0.074902*a+0.006163*girl
physics  = +0.310531*girl+0.300454*boy+0.263659*loves+0.027415*a+0.006760*meson


# 概率潜在语义分析(pLSA)

概率潜在语义分析即潜在语义分析概率化版本，是一种生成模型。

设文档集合为$D=\{d_j\}, j < |D|$，单词集合为$W=\{w_i\}, i < |W|$，文档$d_j$也是单词的序列，序列长度为$|d_j|$（重复单词多次计数。）

概率模型给出文档$d_j$中某一单词位置（比如第一个单词），单词$w_i$出现的概率$P(w_i, d_j)$为
$$
P(w_i, d_j) = 
\sum_k P(w_i, z_k) P(z_k, d_j)
$$
其中$P(z_k, d_j)$为文档$d_j$中某一单词选取话题$z_k$的概率，$P(w_i, z_k)$为话题$z_k$中单词$w_i$出现的概率。

设文档$d_j$第$i^\prime$个单词是单词$w_{i(d_j, i^\prime)}$（$i^\prime < |d_j|$），
则文档$d_j$生成的概率为
$$
\prod_{i^\prime < |d_j|} P(w_{i(d_j, i^\prime)}, d_j)
=\prod_{i < |W|} { P(w_i, d_j)^{n(w_i, d_j)} }
$$
$n(w_i, d_j)$为单词$i$在文档$j$中出现的频次。
所有文档的生成概率的对数为
$$
L = \sum_j \sum_{i} n(w_i, d_j) \log P(w_i, d_j)
$$
优化方法采用EM算法。


In [9]:
ntopics = 2
print("We want %d topics"%ntopics)

lsa = pLSA()
lsa.set_documents(documents)
lsa.topic_decompose(ntopics=ntopics)
lsa.print_mat(topic_names=["live","physics"], max_docs=15)

We want 2 topics
   doc0  = +1.0e+00*physics+2.1e-34*live
   doc1  = +1.0e+00*physics+4.5e-34*live
   doc2  = +1.0e+00*physics+5.2e-46*live
   doc3  = +1.0e+00*physics+5.2e-30*live
   doc4  = +1.0e+00*live+1.7e-30*physics
   doc5  = +1.0e+00*live+9.7e-31*physics
   doc6  = +1.0e+00*live+2.3e-35*physics
   doc7  = +1.0e+00*live+9.3e-30*physics
   doc8  = +6.7e-01*physics+3.3e-01*live
   doc9  = +6.7e-01*physics+3.3e-01*live
  doc10  = +6.7e-01*live+3.3e-01*physics
  doc11  = +7.5e-01*live+2.5e-01*physics
  doc12  = +5.7e-01*live+4.3e-01*physics

   live  = +0.315789*hits+0.315789*photon+0.315789*meson+0.052632*a+0.000000*boy
physics  = +0.333333*loves+0.333333*girl+0.333333*boy+0.000000*meson+0.000000*photon


# 潜在狄利克雷分配(LDA)

设文档集合为$D=\{d_m\}, m<|D|$，单词集合为$W=\{w_i\},i < |W|$，文档$d_j$也是单词的序列，序列长度为$|d_m|$（重复单词多次计数。）。
话题向量为$\mathbf{z}=\{z_m\},m < |D|$。
单词向量为$\mathbf{w} = \{w_{mn}\}, m < |D|, n< |d_m|$。
话题向量为$\mathbf{z} = \{z_{mn}\}, m < |D|, n< |d_m|$。
话题向量先验计数为$\mathbf{\alpha} = \{\alpha_{mk}\}, m < |D|, k < K$。
话题词向量先验计数为$\mathbf{\beta} = \{\beta_{ki}\}, k < K, i < |W|$。


$$
P(\mathbf{w}, \mathbf{z}, \mathbf{\theta},\mathbf{\phi}| \alpha, \beta) = 
\left[\prod_k \text{Dir} (\phi_k|\beta)\right]
\left[\prod_m \text{Dir}(\theta_m|\alpha)\right]
\left[
\prod_{mn} \text{Cat}(z_{mn}|\theta_m) 
\text{Cat}(w_{mn}|\phi_{z_{mn}})
\right]
$$

我们想要求 $P(\mathbf{z},\theta,\phi|\mathbf{w})$
$$P(\mathbf{z},\theta,\phi|\mathbf{w})
=
P(\theta,\phi|\mathbf{z},\mathbf{w})
P(\mathbf{z},\mathbf{w})
/P(\mathbf{w})
=
P(\theta,\phi|\mathbf{z},\mathbf{w})
P(\mathbf{z}|\mathbf{w})
$$
其中

$$
P(\mathbf{z},\mathbf{w}) = \prod_{k} \frac{B(n_k+\beta)}{B(\beta)} \prod_{m} \frac{B(n_m+\alpha)}{B(\alpha)}
$$

和

$$
P(\theta,\phi|\mathbf{z},\mathbf{w})
= \left[\prod_m \text{Dir}(\theta_m|n_m+\alpha)\right] \left[\prod_k \text{Dir}(\phi_k|n_k+\beta)\right]
$$




## Gibbs抽样

$P(\mathbf{z}|\mathbf{w})$可以通过Gibbs抽样方法得到。
注意根据狄利克雷分布，
$\theta_m$ 的期望为 $$(n_m + \alpha)/\sum_k (n_{mk}+\alpha_{mk})$$
$\phi_k$ 的期望为 $$(n_k + \beta)/\sum_{i} (n_{ki}+\beta_{ki})$$

### 初始化

In [10]:
ntopics=2
print("We want %d topics"%ntopics)
lda=LDA()
lda.set_documents(documents)
lda.initialize_randomly(ntopics=ntopics)
print(lda.n_mk)
print(lda.n_m)
print(lda.n_kv)
print(lda.n_k)
print(lda.v_mp)
print(lda.k_mp)

We want 2 topics
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [0. 3.]
 [3. 0.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [0. 3.]
 [3. 0.]
 [3. 3.]
 [4. 4.]
 [0. 0.]]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 0.]
[[6. 4. 3. 5. 6. 6. 1.]
 [5. 5. 6. 5. 5. 4. 1.]]
[31. 31.]
[array([0, 1, 2]), array([2, 1, 0]), array([0, 1, 0]), array([2, 1, 2]), array([3, 4, 5]), array([5, 4, 3]), array([5, 4, 5]), array([3, 4, 3]), array([2, 1, 3]), array([0, 1, 5]), array([3, 4, 0]), array([5, 4, 2, 6]), array([], dtype=int32)]
[array([1, 0, 0]), array([0, 1, 1]), array([1, 0, 1]), array([1, 1, 1]), array([0, 0, 0]), array([1, 0, 1]), array([0, 1, 1]), array([1, 0, 0]), array([1, 1, 1]), array([0, 0, 0]), array([0, 0, 1]), array([1, 0, 0, 1]), array([], dtype=int32)]


### 训练

In [11]:
ntopics=2
print("We want %d topics"%ntopics)
lda=LDA()
lda.set_documents(documents)
lda.topic_decompose(ntopics = ntopics, alpha = 1, beta = 1)
lda.print_mat()

We want 2 topics
   doc0  = +5.7e-01*topic0+4.3e-01*topic1
   doc1  = +6.1e-01*topic1+3.9e-01*topic0
   doc2  = +6.8e-01*topic1+3.2e-01*topic0
   doc3  = +6.4e-01*topic0+3.6e-01*topic1
   doc4  = +6.0e-01*topic0+4.0e-01*topic1
   doc5  = +6.2e-01*topic0+3.8e-01*topic1
   doc6  = +6.4e-01*topic1+3.6e-01*topic0
   doc7  = +7.0e-01*topic0+3.0e-01*topic1
   doc8  = +5.7e-01*topic0+4.3e-01*topic1
   doc9  = +6.9e-01*topic1+3.1e-01*topic0

 topic0  = +0.266818*hits+0.205121*meson+0.186861*boy+0.160548*loves+0.075752*girl
 topic1  = +0.308973*photon+0.246785*girl+0.155302*loves+0.127163*boy+0.084368*meson


# 20新闻组数据集

## 下载停止词汇

In [12]:
if False:
    import nltk
    from nltk.corpus import stopwords
    
    # downaload stop words
    nltk.download('stopwords')
    
    stop_words = stopwords.words('english')
else:
    # I download for you, and save it for you
    stop_words = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

stop_words.extend(string.ascii_letters)
stop_words.extend(["would"])
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

## 20新闻组语料库

语料库取自 http://qwone.com/~jason/20Newsgroups/ 。
你也可以在sklearn中找到这个数据集。
在 https://raw.githubusercontent.com/selva86/datasets/master/newsgroups.json 包含json格式的数据。

In [13]:
#%%bash
#wget 'https://raw.githubusercontent.com/selva86/datasets/master/newsgroups.json' -O newsgroups.json

In [14]:
import pandas as pd
from IPython.display import display

df = pd.read_json('./newsgroups.json')


#df = df.head(1000)
#display(df)

email_documents = df.content.values.tolist()
target_names = df.target_names.values.tolist()
targets = df.target.values.tolist()

n_catogories = len(df.target.unique())
catogories = range(n_catogories)
cat_names = n_catogories*[None]

for i, t in enumerate(targets):
    cat_names[t] = target_names[i]
print(cat_names) 

#print(email_documents[10])
#print(target_names[10])

display(df.head(n=20))

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


content  target  \
0      From: lerxst@wam.umd.edu (where's my thing)\nS...       7   
1      From: guykuo@carson.u.washington.edu (Guy Kuo)...       4   
10     From: irwin@cmptrc.lonestar.org (Irwin Arnstei...       8   
100    From: tchen@magnus.acs.ohio-state.edu (Tsung-K...       6   
1000   From: dabl2@nlm.nih.gov (Don A.B. Lindbergh)\n...       2   
10000  From: a207706@moe.dseg.ti.com (Robert Loper)\n...       7   
10001  From: kimman@magnus.acs.ohio-state.edu (Kim Ri...       6   
10002  From: kwilson@casbah.acns.nwu.edu (Kirtley Wil...       2   
10003  Subject: Re: Don't more innocents die without ...       0   
10004  From: livesey@solntze.wpd.sgi.com (Jon Livesey...       0   
10005  From: dls@aeg.dsto.gov.au (David Silver)\nSubj...       1   
10006  Subject: Re: Mike Francesa's 1993 Predictions\...       9   
10007  From: jet@netcom.Netcom.COM (J. Eric Townsend)...       8   
10008  From: gld@cunixb.cc.columbia.edu (Gary L Dare)...      10   
10009  From: sehari@iastate.edu (Babak Sehari)\nSubje...      12   
1001   From: danmg@grok85.ColumbiaSC.NCR.COM (Daniel ...       7   
10010  From: henry@zoo.toronto.edu (Henry Spencer)\nS...      14   
10011  From: tzs@stein2.u.washington.edu (Tim Smith)\...      18   
10012  From: U56149@uicvm.uic.edu\nSubject: LCIII & M...       4   
10013  From: nsmca@aurora.alaska.edu\nSubject: Lunar ...      14   

                  target_names  
0                    rec.autos  
1        comp.sys.mac.hardware  
10             rec.motorcycles  
100               misc.forsale  
1000   comp.os.ms-windows.misc  
10000                rec.autos  
10001             misc.forsale  
10002  comp.os.ms-windows.misc  
10003              alt.atheism  
10004              alt.atheism  
10005            comp.graphics  
10006       rec.sport.baseball  
10007          rec.motorcycles  
10008         rec.sport.hockey  
10009          sci.electronics  
1001                 rec.autos  
10010                sci.space  
10011       talk.politics.misc  
10012    comp.sys.mac.hardware  
10013                sci.space

## 预处理
sklearn提供了这个数据集的预处理选项，但是我们自己做。

In [15]:
import re

shown=0
print("'''''%s'''''"%email_documents[shown])

# remove email header
email_documents = ["\n\n".join(doc.split('\n\n')[1:]) for doc in email_documents]

# Remove Emails
email_documents = [re.sub('\S*@\S*\s?', '', doc) for doc in email_documents]

print("'''''%s'''''"%email_documents[shown])

'''''From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----




'''''
''''' I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from 

## 结构化数据

In [16]:
email_sdocs=StructuredDocuments()
email_sdocs.set_documents(email_documents, stop_words=stop_words, threshold=5)
email_sdocs.print_info(n=10)

23417 terms found in 11314 documents.
terms: ['wondering', 'anyone', 'could', 'enlighten', 'car', 'saw', 'day', 'door', 'sports', 'looked', 'late', 'early', 'called', 'doors', 'really', 'small', 'addition', 'front', 'bumper', 'separate']
terms_set: ['gravitational', 'handlebars', 'exug', 'username', 'install', 'settling', 'ornaments', 'soldered', 'ernest', 'jonathan', 'suffix', 'archbishop', 'hardcover', 'swung', 'glossy', 'jubilee', 'poly', 'nz', 'elastic', 'modify']
term_to_index: [('wondering', 0), ('anyone', 1), ('could', 2), ('enlighten', 3), ('car', 4), ('saw', 5), ('day', 6), ('door', 7), ('sports', 8), ('looked', 9)]
docs_terms: [['wondering', 'anyone', 'could', 'enlighten', 'car', 'saw', 'day', 'door', 'sports', 'car'], ['fair', 'number', 'brave', 'souls', 'upgraded', 'SI', 'clock', 'oscillator', 'shared', 'experiences'], ['line', 'Ducati', 'GTS', 'model', 'clock', 'Runs', 'well', 'paint', 'bronze', 'brown'], ['Software', 'publishing', 'windows', 'OCR', 'System', 'Windows', 'O

## SVD_LSA

In [17]:
N_topics=50
svd=True
if svd:
    svd_lsa=SVD_LSA()
    svd_lsa.set_structured_documents(email_sdocs)
    svd_lsa.topic_decompose(ntopics=N_topics)

In [28]:
def print_lsa(lsa):
    
    topic_weights=np.zeros((n_catogories, lsa.ntopics))
    for cat in range(n_catogories):
        #print(nmf_lsa.topic_doc_mat[:,np.equal(targets, cat+1)])
        target = catogories[cat]        
        topic_weight = lsa.topic_doc_mat[:,np.equal(targets, target)].mean(axis=1)
        topic_weights[cat,:] = topic_weight[:]
        
        index = np.argsort(-topic_weight)
        print("(%2d)%30s topic%02d(%.1e) topic%02d(%.1e) topic%02d(%.1e)"%\
              (target, "%s"%(cat_names[target]), index[0], topic_weight[index[0]], index[1],topic_weight[index[1]], index[2], topic_weight[index[2]]   ) )

    for topic in range(lsa.ntopics):
        cats_weights = topic_weights[:,topic]
        cats_weights = cats_weights
        index = np.argsort(-cats_weights)
        cat0 = index[0]
        cat1 = index[1]
        cat2 = index[2]
        print("%15s %25s(%.1e) %25s(%.1e) %25s(%.1e)"%\
              ("topic%d"%topic,
               cat_names[cat0], cats_weights[cat1], \
               cat_names[cat1], cats_weights[cat1],\
               cat_names[cat2], cats_weights[cat2] ) )

    #print(targets[:10])
if svd:
    svd_lsa.print_mat(max_topics=100)
    print_lsa(svd_lsa)    

   doc0  = -1.5e-02*topic43-1.4e-02*topic39-1.2e-02*topic35+1.2e-02*topic30-1.1e-02*topic11-1.0e-02*topic42-1.0e-02*topic38-1.0e-02*topic4+1.0e-02*topic12-9.9e-03*topic29+9.0e-03*topic3+8.9e-03*topic44+8.9e-03*topic41-8.5e-03*topic27+8.2e-03*topic48+7.4e-03*topic22-7.2e-03*topic21-7.0e-03*topic34+7.0e-03*topic36+6.2e-03*topic14+6.0e-03*topic26+5.3e-03*topic17-5.0e-03*topic19-4.7e-03*topic45+4.6e-03*topic33+4.1e-03*topic18-2.8e-03*topic13+2.7e-03*topic28-2.6e-03*topic15-2.5e-03*topic47+2.1e-03*topic46-2.1e-03*topic23+1.9e-03*topic32-1.8e-03*topic31+1.5e-03*topic10+1.5e-03*topic40+1.2e-03*topic20+8.0e-04*topic37-7.7e-04*topic49-6.9e-04*topic25+5.6e-04*topic16+4.4e-04*topic5+3.8e-04*topic7-3.7e-04*topic9-3.7e-04*topic8+3.1e-04*topic1-1.4e-04*topic6+1.2e-04*topic24-2.7e-05*topic2-5.0e-06*topic0
   doc1  = -8.9e-03*topic42-8.2e-03*topic48+7.6e-03*topic45+7.0e-03*topic14+6.6e-03*topic3-6.5e-03*topic4-6.4e-03*topic40+5.1e-03*topic49+4.7e-03*topic31+4.5e-03*topic12-4.5e-03*topic9-4.5e-03*topic

topic39  = +0.215626*dolven+0.213485*doug-0.211959*luck+0.195658*update+0.181144*frank
topic40  = +0.579089*andreas+0.246576*looking+0.215149*frank+0.186492*system+0.180335*subroutine
topic41  = +0.433805*luck+0.358644*frank+0.276527*system+0.251730*good-0.206991*andreas
topic42  = +0.471582*luck+0.257240*good-0.216490*frank+0.215495*israel+0.198146*scsi
topic43  = -0.348439*scsi+0.235920*hp+0.215427*drive+0.193563*xman+0.180738*version
topic44  = -0.273211*israel+0.202215*update+0.199538*scsi-0.194714*simms-0.174045*birthday
topic45  = +0.265043*update+0.236029*andreas+0.233589*address-0.192630*title-0.179516*frank
topic46  = +0.293209*title+0.275721*lee-0.256636*graphics+0.252949*says-0.200686*kingman
topic47  = -0.304404*key+0.304332*graphics+0.224441*comp+0.191617*xman+0.183213*hp
topic48  = -0.336108*graphics-0.222208*comp+0.191105*xman+0.175928*go-0.169615*title
topic49  = +0.348572*go+0.214125*graphics+0.176310*israel-0.154063*steve-0.151818*barber
( 0)                   alt.ath

## NMF_LSA

In [19]:
#N_topics = 3+0*min(3, n_catogories)
print("We want %d topics"%N_topics)

nmf_lsa = NMF_LSA()
nmf_lsa.set_structured_documents(email_sdocs)
def on_update(i, W, H, Wold, Hold):
    if i % 10 == 0:
        dH = H - Hold
        dW = W - Wold
        print("[%5d] dH"%i, np.einsum("ij,ij", dH, dH))
        print("[%5d] dW"%i, np.einsum("ij,ij", dW, dW))
    
nmf_lsa.topic_decompose(ntopics=N_topics, max_iters=200, on_update=on_update)

We want 50 topics
[    0] dH 390635.7417046184
[    0] dW 131670.00633145001
[   10] dH 0.03638915386063681
[   10] dW 1711.6659096919473
[   20] dH 0.005138609272494576
[   20] dW 324.7977598088766
[   30] dH 0.001649956745203241
[   30] dW 43.71345372077325
[   40] dH 0.0007219224249530767
[   40] dW 25.80647424711721
[   50] dH 0.0008466947759816882
[   50] dW 10.054346958888729
[   60] dH 0.0012924378149829251
[   60] dW 15.608590911959931
[   70] dH 0.00112271097045587
[   70] dW 2.291987281516485
[   80] dH 0.00011165490260669117
[   80] dW 1.989792427565592
[   90] dH 8.181907620457356e-05
[   90] dW 1.3495021407496701
[  100] dH 0.0002073055769586335
[  100] dW 2.3270420434329404
[  110] dH 0.00048241347558258666
[  110] dW 1.9268805983085175
[  120] dH 0.0003356295011990144
[  120] dW 3.6280756411343136
[  130] dH 0.0003835967681604186
[  130] dW 0.7016947752416887
[  140] dH 0.00019912333698075444
[  140] dW 0.3947426422453327
[  150] dH 3.535898832286113e-05
[  150] dW 0.372

In [20]:
from IPython import display
display.display(df.head(n=5))
nmf_lsa.print_mat(max_docs=5, max_topics=100, max_terms=5)
print_lsa(nmf_lsa)
print("should be close to one:", nmf_lsa.topic_doc_mat.sum(axis=0))

content  target  \
0     From: lerxst@wam.umd.edu (where's my thing)\nS...       7   
1     From: guykuo@carson.u.washington.edu (Guy Kuo)...       4   
10    From: irwin@cmptrc.lonestar.org (Irwin Arnstei...       8   
100   From: tchen@magnus.acs.ohio-state.edu (Tsung-K...       6   
1000  From: dabl2@nlm.nih.gov (Don A.B. Lindbergh)\n...       2   

                 target_names  
0                   rec.autos  
1       comp.sys.mac.hardware  
10            rec.motorcycles  
100              misc.forsale  
1000  comp.os.ms-windows.misc

   doc0  = +1.1e+00*topic0+2.3e-01*topic18+6.8e-02*topic46+6.1e-02*topic8+1.4e-02*topic41+1.1e-02*topic12+9.4e-03*topic25+6.7e-03*topic39+2.0e-03*topic9+1.5e-03*topic3+8.0e-04*topic6+6.6e-05*topic30+3.6e-05*topic4+3.2e-05*topic48+1.5e-07*topic36+8.1e-08*topic24+6.5e-11*topic10+1.7e-20*topic31+3.9e-22*topic14+1.2e-23*topic22+9.0e-27*topic7+7.4e-30*topic45+2.1e-36*topic33+7.9e-37*topic37+2.7e-43*topic2+1.8e-51*topic17+1.7e-58*topic23+1.5e-59*topic20+4.0e-61*topic43+6.3e-62*topic27+6.9e-68*topic15+2.6e-69*topic47+9.7e-74*topic29+7.8e-75*topic1+4.5e-78*topic21+2.3e-81*topic16+2.8e-82*topic5+5.0e-87*topic49+2.0e-92*topic28+3.1e-107*topic35+5.6e-111*topic11+3.0e-126*topic26+5.4e-143*topic38+3.1e-145*topic13+2.2e-177*topic34+2.0e-281*topic32+0.0e+00*topic40+0.0e+00*topic42+0.0e+00*topic44+0.0e+00*topic19
   doc1  = +2.4e-01*topic0+2.2e-01*topic35+1.4e-01*topic18+5.4e-02*topic5+3.7e-02*topic43+3.1e-02*topic7+3.0e-02*topic8+2.1e-02*topic37+1.7e-02*topic22+1.2e-02*topic14+9.6e-03*topic9+8.1e-03*

## pLSA

In [21]:
#N_topics = 3+0*min(3, n_catogories)
print("We want %d topics"%N_topics)

plsa=pLSA()
plsa.set_structured_documents(email_sdocs)
plsa.topic_decompose(ntopics=N_topics, on_update=on_update)

We want 50 topics
[    0] dH 173731.00311718334
[    0] dW 0.13011962473768077
[   10] dH 43.75320931600517
[   10] dW 0.0021964432192927
[   20] dH 10.16039695897526
[   20] dW 0.0002167466490720534
[   30] dH 3.744576559969413
[   30] dW 7.880204684271022e-05
[   40] dH 1.8026573102677164
[   40] dW 7.4008139353296e-05
[   50] dH 0.9815556203840963
[   50] dW 3.181144416666826e-05
[   60] dH 0.643131947909195
[   60] dW 8.160193563109852e-06
[   70] dH 0.4356999012240623
[   70] dW 5.438912617495792e-06
[   80] dH 0.3274124685320499
[   80] dW 3.334353922541182e-06
[   90] dH 0.28487979204805475
[   90] dW 2.3489638388330787e-06
[  100] dH 0.22366845884589548
[  100] dW 2.3851281172306353e-06
[  110] dH 0.19107847119341528
[  110] dW 1.8914145464074424e-06
[  120] dH 0.18863249233578083
[  120] dW 1.6858389152326332e-06
[  130] dH 0.14554042030697056
[  130] dW 1.2898878085676262e-06
[  140] dH 0.18710525757715668
[  140] dW 1.3842593849492278e-06
[  150] dH 0.13534173982820527
[  15

In [29]:
plsa.print_mat(max_docs=10, max_terms=3, max_topics=100)
print_lsa(plsa)

   doc0  = +4.6e-01*topic0+2.9e-01*topic13+1.8e-01*topic27+3.8e-02*topic11+2.9e-02*topic5+6.4e-04*topic46+2.0e-05*topic20+1.3e-08*topic12+5.9e-09*topic8+1.2e-09*topic3+1.1e-09*topic42+6.0e-10*topic38+4.2e-10*topic24+4.1e-10*topic43+2.8e-10*topic49+2.7e-10*topic7+1.6e-10*topic2+1.4e-10*topic48+1.3e-10*topic33+1.1e-10*topic39+1.1e-10*topic6+1.0e-10*topic26+8.8e-11*topic17+6.5e-11*topic41+4.7e-11*topic14+4.1e-11*topic36+3.9e-11*topic35+3.5e-11*topic29+3.3e-11*topic23+1.8e-11*topic22+1.6e-11*topic4+1.0e-11*topic1+7.0e-12*topic47+4.3e-12*topic15+2.5e-12*topic44+2.3e-12*topic18+1.4e-12*topic32+1.1e-12*topic25+2.8e-13*topic34+2.2e-13*topic10+1.3e-13*topic21+4.6e-14*topic40+1.9e-14*topic45+1.5e-15*topic30+1.0e-18*topic19+3.7e-22*topic16+3.5e-24*topic9+1.9e-24*topic28+1.1e-24*topic31+1.4e-36*topic37
   doc1  = +3.1e-01*topic47+2.8e-01*topic8+1.3e-01*topic29+1.3e-01*topic13+1.3e-01*topic9+1.6e-02*topic33+7.1e-03*topic36+5.4e-06*topic40+2.6e-06*topic4+5.7e-08*topic26+8.0e-09*topic25+5.0e-09*topic

## LDA

In [23]:
if False:
    N_topics = 3+0*min(3, n_catogories)
    print("We want %d topics"%N_topics)
    lda=LDA()
    lda.set_structured_documents(email_sdocs)
    lda.topic_decompose(ntopics=N_topics)

In [24]:
if False:
    lda.print_mat(max_docs=10, max_terms=3)
    print_lsa(lda)

# Bakcups
## 随机梯度下降 (Stochastic gradient descent)

we want to maximize
$$
P(\theta, \phi|\mathbf{w}) = \sum_{z}P(\theta, \phi|\mathbf{z}, \mathbf{w}) P(\mathbf{z}|\mathbf{w})
$$

then we need
$$
\partial_\theta P(\theta, \phi|\mathbf{w})
=
\partial_\theta \sum_{z}P(\theta, \phi|\mathbf{z}, \mathbf{w}) P(\mathbf{z}|\mathbf{w})
=
\sum_{z} P(\mathbf{z}|\mathbf{w}) \partial_\theta P(\theta, \phi|\mathbf{z}, \mathbf{w})
=0
$$

similarly
$$
\sum_{z} P(\mathbf{z}|\mathbf{w}) \partial_\phi P(\theta, \phi|\mathbf{z}, \mathbf{w})
=0
$$


We can sample $z$ with probability of $P(\mathbf{z}|\mathbf{w})$, and move $\theta$ and $\phi$ along the direction of 
$-\partial_\theta P(\theta, \phi|\mathbf{z}, \mathbf{w})$ and $-\partial_\phi P(\theta, \phi, \mathbf{z}|\mathbf{w})$, respectively.
(At least) for small engouh the step, we will reach the statination point.
But it's often bad to use gradient decent method with probablity (we should use log(probablity)). 

we write it in the form of 
$$
P(\theta, \phi|\mathbf{w}) 
=
\sum_{z} P(\theta, \phi, \mathbf{z}, \mathbf{w})/P(\mathbf{w})
=
\sum_{z} P(\mathbf{z}, \mathbf{w} | \theta, \phi)P(\theta,\phi)/P(\mathbf{w})
$$

### the pLSA
EM algoirhtm, we define the Q function as
$$
\sum_{z} P(\mathbf{z} | \mathbf{w}, \theta^i, \phi^i) \log  P(\mathbf{z}, \mathbf{w}|\theta, \phi)
$$
We to maximize to Q (with constraint of $\sum_k \theta_{mk}=1$, or normalize in time)
$$
\partial_\theta \sum_{z}  P(\mathbf{z} | \mathbf{w}, \theta^i, \phi^i) \log  P(\mathbf{z}, \mathbf{w}|\theta, \phi) = 0
$$
$$
\sum_{z}  P(\mathbf{z} | \mathbf{w}, \theta^i, \phi^i) \partial_\theta \log  P(\mathbf{z}, \mathbf{w}|\theta, \phi) = 0
$$


We can sample $z$ with probability of $ P(\mathbf{z} | \mathbf{w}, \theta^i, \phi^i)$, and move $\theta$ and $\phi$ along the direction of 
$-\partial_\theta \log  P(\mathbf{z}, \mathbf{w}|\theta, \phi)$ and $-\partial_\phi \log  P(\mathbf{z}, \mathbf{w}|\theta, \phi)$, respectively.
The update ruler
$$
\theta^{i+1} = \theta + \eta \partial_\theta \log  P(\mathbf{z}, \mathbf{w}|\theta, \phi)
$$
$$
\phi^{i+1} = \phi + \eta \partial_\phi\log  P(\mathbf{z}, \mathbf{w}|\theta, \phi)
$$

It's simple that
$$
\log P(\mathbf{z},\mathbf{w}|\theta,\phi)
=
\prod_{mn} \text{Cat}(z_{mn}|\theta_m) 
\text{Cat}(w_{mn}|\phi_{z_{mn}})
$$
then
$$
\partial_{\theta_m} \log P(\mathbf{z},\mathbf{w}|\theta,\phi)
=
n_m/\theta_m
$$
$$
\partial_{\phi_k} \log P(\mathbf{z},\mathbf{w}|\theta,\phi)
=
n_k/\phi_k
$$

Excisie:
Note the normalized pdf of $\mathbf{z}$ and $\mathbf{w}$ should be
$$
P(\mathbf{z}, \mathbf{w}|\theta, \phi)
 =
P(\mathbf{z}, \mathbf{w}, \theta, \phi)/P(\theta, \phi)
 =
P(\theta, \phi | \mathbf{z}, \mathbf{w}) P(\mathbf{z}, \mathbf{w})/P(\theta, \phi)
$$

we just recall
$$
P(\theta, \phi)
=
\left[\prod_k \text{Dir} (\phi_k|\beta)\right]
\left[\prod_m \text{Dir}(\theta_m|\alpha)\right]
$$

$$
\log P(\mathbf{z},\mathbf{w}|\theta,\phi)
= 
\log P(\mathbf{z}, \mathbf{w})
+ \log \left[\prod_m \text{Dir}(\theta_m|n_m+\alpha)\right]
+\log\left[\prod_k \text{Dir}(\phi_k|n_k+\beta)\right]
-\log \left[\prod_m \text{Dir}(\theta_m|\alpha)\right]
-\log \left[\prod_k \text{Dir} (\phi_k|\beta)\right]
$$
we can again obtain the $P(\mathbf{z}, \mathbf{w}|\theta, \phi)$

and 
$$
P(\mathbf{z} |\mathbf{w}, \theta, \phi)
=
P(\mathbf{z}, \mathbf{w} | \theta, \phi)/ P(\mathbf{w}|\theta, \phi)
\propto
\theta_{mk} \phi_{kn}
$$
for the document $m$ and word $n$




### the LDA
Like EM algoirhtm, we define the Q function as
$$
\sum_{z} P(\mathbf{z}, \mathbf{w}, \theta^i, \phi^i) \log  P(\mathbf{z}, \mathbf{w}, \theta, \phi)
$$
We to maximize to Q (with constraint of $\sum_k \theta_{mk}=1$, or normalize in time)
$$
\partial_\theta \sum_{z}  P(\mathbf{z}, \mathbf{w}, \theta^i, \phi^i) \log  P(\mathbf{z}, \mathbf{w}, \theta, \phi) = 0
$$
$$
\sum_{z}  P(\mathbf{z}, \mathbf{w}, \theta^i, \phi^i) \partial_\theta \log  P(\mathbf{z}, \mathbf{w}, \theta, \phi) = 0
$$


We can sample $z$ with probability of $ P(\mathbf{z}, \mathbf{w}, \theta^i, \phi^i)$, and move $\theta$ and $\phi$ along the direction of 
$-\partial_\theta \log  P(\mathbf{z}, \mathbf{w}, \theta, \phi)$ and $-\partial_\phi \log  P(\mathbf{z}, \mathbf{w}, \theta, \phi)$, respectively.
The update ruler
$$
\theta^{i+1} = \theta + \eta \partial_\theta \log  P(\mathbf{z}, \mathbf{w}, \theta, \phi)
$$
$$
\phi^{i+1} = \phi + \eta \partial_\phi\log  P(\mathbf{z}, \mathbf{w}, \theta, \phi)
$$

It's simple that
$$
\partial_{\theta_m} \log P(\mathbf{z},\mathbf{w}, \theta,\phi)
=
(n_m + \alpha - 1)/\theta_m
$$
$$
\partial_{\phi_k} \log P(\mathbf{z},\mathbf{w}, \theta,\phi)
=
(n_k + \beta - 1)/\phi_k
$$

and 
$$
P(\mathbf{z}, \mathbf{w}, \theta, \phi)
\propto
\theta_{mk} \phi_{kn}
$$
for the document $m$ and word $n$


In [25]:
alpha=1.0
beta=1.0

theta_mk = np.random.rand(len(documents), ntopics)
theta_mk = theta_mk / theta_mk.sum(axis=1, keepdims=True)
phi_kv = np.random.rand(ntopics, len(terms_vec))
phi_kv = phi_kv / phi_kv.sum(axis=1, keepdims=True)

def zwtp_Gibbs_topic_prob(m, v):    
    return theta_mk[m,:] * phi_kv[:,v]

def zwtp_MH_topic_prob(m, v, k):
    return theta_mk[m, k] * phi_kv[k, v]

intialize_randomly()

# warnming
for _ in range(1000):
    Gibbs_step(zwtp_Gibbs_topic_prob)

def normalize(mat):
    return mat/mat.sum(axis=1, keepdims=True)
    
eta = 0.01
for _ in range(1000):
    MH_step(zwtp_MH_topic_prob)
    
    #print(n_mk[:,:] + alpha - 1)
    #print(theta_mk)
    d = (n_mk[:,:] + alpha - 1)/theta_mk[:,:]
    theta_mk = theta_mk + eta*d
    theta_mk = normalize(theta_mk)
    
    d = (n_kv[:,:] + beta - 1)/phi_kv[:,:]
    phi_kv = phi_kv + eta*d
    phi_kv = normalize(phi_kv)
    
    #print(theta_mk)
    #print(phi_kv)
    #print_mat(n_kv.transpose(), n_mk.transpose())
    #print(theta_mk.sum(axis=1))
    #print(phi_kv.sum(axis=1))
    #print(k_mn)
    #print(n_kv)
    #print(n_mk)
    
print_mat(phi_kv.transpose(), theta_mk.transpose())

NameError: name 'terms_vec' is not defined

In [ ]:
[1,2][0:2]